### ISSUE TITLE
IdentityWeakReference should be IDisposable

### ISSUE THREAD

**Issue by felipepessoto** [apache/lucenenet#506]
IdentityWeakReference inherits from WeakReference, which has a finalizer, but its finalizer is especially handled by CLR to be ignored:

![image](https://user-images.githubusercontent.com/1336227/129139847-313afdc4-143a-4c9b-9e0b-b5b518facb28.png)
https://referencesource.microsoft.com/#mscorlib/system/weakreference.cs,108

When you inherit the WeakReference CLR doesn't ignore the finalizer anymore and the object become finalizable. IdentityWeakReference doesn't supress finalization causing a huge pressure on finalizer thread.

In one of my traces I found a 5 seconds GC pause due to that, the pause was not in GC itself, but in the suspension phase before starting the GC. I tracked what the SuspendEE was waiting, and it was the finalizer thread. When investigating why finalizer was hanging, I found this:

![image](https://user-images.githubusercontent.com/1336227/129138699-d1ec5926-1a84-4555-80d6-97b719b5fafe.png)

IdentityWeakReference  should implement IDisposable and call GC.SuppressFinalize(this) in Dispose method.
And all instances of IdentityWeakReference  needs to call Dispose before losing the reference, for example: 

![image](https://user-images.githubusercontent.com/1336227/129140503-313eba81-7ec6-4ccc-ba7c-0c0d352fa528.png)

You can easily simulate the issue using this code and uncomment the lines to fix it:

```
static object x = new object();

static async Task Main(string[] args)
{
    const int count = 1000000;

    var weaks = new List<IdentityWeakReference<object>>(count);
    for (int i = 0; i < count; i++)
    {
        weaks.Add(new IdentityWeakReference<object>(x));
    }

    Console.WriteLine("Start Perfview collection and press Enter");
    Console.ReadLine();

    GC.KeepAlive(weaks);

    for (int i = 0; i < count; i++)
    {
        //weaks[i].Dispose();
    }

    weaks = null;

    Stopwatch c = Stopwatch.StartNew();

    GC.Collect(2, GCCollectionMode.Default, true, true);
    GC.WaitForPendingFinalizers();
    GC.Collect(2, GCCollectionMode.Default, true, true);
    GC.WaitForPendingFinalizers();

    Console.WriteLine("GC DONE. Stop Perfview");
    Console.WriteLine($"{c.ElapsedMilliseconds}ms");
    Console.ReadLine();
}

internal class IdentityWeakReference<T> : WeakReference
    //, IDisposable 
    where T : class
{
    private readonly int hash;
    private static readonly object NULL = new object();
    //private bool disposedValue;

    public IdentityWeakReference(T target)
        : base(target ?? NULL)
    {
        hash = RuntimeHelpers.GetHashCode(target);
    }

    public override int GetHashCode()
    {
        return hash;
    }

    public override bool Equals(object o)
    {
        if (ReferenceEquals(this, o))
        {
            return true;
        }
        if (o is IdentityWeakReference<T> iwr && ReferenceEquals(this.Target, iwr.Target))
        {
            return true;
        }
        return false;
    }

    public new T Target
    {   // note: if this.NULL is the target, it will not cast to T, so the "as" will return null as we would expect.
        get => base.Target as T;
        set => base.Target = value;
    }

    //protected virtual void Dispose(bool disposing)
    //{
    //    if (!disposedValue)
    //    {
    //        if (disposing)
    //        {
    //            // TODO: dispose managed state (managed objects)
    //        }

    //        // TODO: free unmanaged resources (unmanaged objects) and override finalizer
    //        // TODO: set large fields to null
    //        disposedValue = true;
    //    }
    //}

    //public void Dispose()
    //{
    //    // Do not change this code. Put cleanup code in 'Dispose(bool disposing)' method
    //    Dispose(disposing: true);
    //    GC.SuppressFinalize(this);
    //}
}
```

### GC Stats without the fix:

![image](https://user-images.githubusercontent.com/1336227/129139311-94e24b13-a04e-48aa-9e69-b88a4e6dd5b9.png)

And even this application doing nothing. GC takes 5 seconds (technically not GC, but Finalizer):

![image](https://user-images.githubusercontent.com/1336227/129139342-cedec7be-83ff-452b-a95e-beb876d5f089.png)

![image](https://user-images.githubusercontent.com/1336227/129139242-3626ce57-d3a1-4894-a163-3f6f1aff137b.png)

### GC Stats with the fix:

No Finalized Objects

GC is almost instantaneous, as expected

![image](https://user-images.githubusercontent.com/1336227/129139403-9622bcc2-b374-4b36-adbe-09de20d7f624.png)

**Comment by felipepessoto** [comment]
Looks like it has been fixed: https://github.com/apache/lucenenet/pull/236. Can you please confirm?

**Comment by eladmarg** [comment]
Thanks @felipepessoto
I'm sure there is still some edge case for this weak reference.

I'm still getting #319 on production, so this might be the issue with it.
I couldn't reproduce this but it's still happening very rarely, (once in few days) when there is a high load

**Comment by NightOwl888** [comment]
@felipepessoto 

Thanks for the report and your insights. I took a closer look and it seems there is more wrong with this than simply not correctly disposing the weak reference. The original declaration in Lucene's `IndexReader` was:

```java
  private final Set<IndexReader> parentReaders = 
      Collections.synchronizedSet(Collections.newSetFromMap(new WeakHashMap<IndexReader,Boolean>()));
```

However, ours is:

```c#
private readonly ISet<IdentityWeakReference<IndexReader>> parentReaders = new ConcurrentHashSet<IdentityWeakReference<IndexReader>>();
```

Effectively, we have replaced a collection that automatically prunes its weak entries with one that does not.

It seems like the right direction to go here is to factor out the `IdentityWeakReference<T>` class (which is only referenced in `IndexReader`) and replace the collection with `ConditionalWeakTable<TKey, TValue>`, since it would automatically prune and GC the contained keys correctly and it more closely resembles how it was done in Lucene. While there was no "identity" equality comparison in the original Java WeakHashMap, the object that is being compared (`IndexReader`) overrides `GetHashCode()` and `Equals()` to make the identity comparison, so the fact that `ConditionalWeakTable<TKey, TValue>` uses identity comparison is no issue.

Unfortunately, if we do that we need to conditionally compile because the enumerator is not exposed in `ConditionalWeakTable<TKey, TValue>` prior to .NET Stanadard 2.1. So, we will need to fall back to `WeakDictionary<TKey, TValue>` in those cases.

In addition, there is a thread safety issue. The lock of the concurrent set in Java was shared between the `Add` operation and the enumeration, which means we can add items while they are being iterated even though that is not supposed to be allowed.

This report also led me to discover http://www.philosophicalgeek.com/2014/08/14/prefer-weakreferencet-to-weakreference/, which recommends against using the generic `WeakReference` and instead use `WeakReference<T>`, so we can also make some adjustments to [`WeakDictionary<TKey, TValue>`](https://github.com/apache/lucenenet/blob/Lucene.Net_4_8_0_beta00014/src/Lucene.Net/Support/WeakDictionary.cs#L255) in order to make it more robust.

**Comment by NightOwl888** [comment]
I have submitted #509 with a patch to fix the issues with using the wrong collection type.

- .NET Standard 2.1 uses `ConditionalWeakTable<TKey, TValue>`
- Lower .NET versions use `WeakDictionary<TKey, TValue>`
  - The `WeakKey<T>` class (used by `WeakDictionary<TKey, TValue>`) was modified to be backed by `WeakReference<T>` rather than `WeakReference`
  - `WeakDictionary<TKey, TValue>` was modified to be backed by `ConcurrentDictionary<TKey, TValue>` to allow the reap to happen while doing a forward iteration

You can download a CI build of the changes from [here](https://dev.azure.com/LuceneNET-Temp/Lucene.NET/_build/results?buildId=1463&view=artifacts&pathAsName=false&type=publishedArtifacts), and I would appreciate your help testing them to ensure the problem is resolved.

> When you inherit the WeakReference CLR doesn't ignore the finalizer anymore and the object become finalizable. 

Being that we switched to a wrapped (rather than inherited) instance, I suspect the finalizer issue has been sidestepped. However, if there is still an issue with it, please let us know.

Do note that because of the conditional compilation branching it would be helpful to know which .NET platform you are targeting going forward so we know which implementation you are referring to.

**Comment by eladmarg** [comment]
Thanks a lot. 

I'm asking myself, do we really need to support older platforms? How many of the user base won't be supported? This reminds me the days of supporting IE6 browser. Besides even if you have an old legacy system you can always run the Lucene search as external api service 

I'll push the version in two days and let you know.

We won't be able to know immediately if this resolved, we'll have to wait about a week to ensure this isn't occurred again

I'm using netcore 5.0

**Comment by eladmarg** [comment]
So far looks promising 
Let's wait more couple of days, seems like it resolved

**Comment by eladmarg** [comment]
fixed.

**Comment by felipepessoto** [comment]
In which commit?

**Comment by eladmarg** [comment]
> In which commit?

#509

**Comment by felipepessoto** [comment]
@NightOwl888 do you have any ETA when next release will be done?
